package tables;

// Generated 10.05.2016 10:16:44 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cinema generated by hbm2java
 */
@Entity
@Table(name = "cinema", catalog = "cinema")
public class Cinema implements java.io.Serializable {

	private int cinemaId;
	private String name;
	private int halls;
	private String address;
	private Set<Seans> seanses = new HashSet<Seans>(0);

	public Cinema() {
	}

	public Cinema(String name, int halls, String address) {
		this.name = name;
		this.halls = halls;
		this.address = address;
	}

	public Cinema(String name, int halls, String address, Set<Seans> seanses) {
		this.name = name;
		this.halls = halls;
		this.address = address;
		this.seanses = seanses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cinema_id", unique = true, nullable = false)
	public int getCinemaId() {
		return this.cinemaId;
	}

	public void setCinemaId(int cinemaId) {
		this.cinemaId = cinemaId;
	}

	@Column(name = "name", nullable = false, length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "halls", nullable = false)
	public int getHalls() {
		return this.halls;
	}

	public void setHalls(int halls) {
		this.halls = halls;
	}

	@Column(name = "address", nullable = false, length = 65535)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cinema")
	public Set<Seans> getSeanses() {
		return this.seanses;
	}

	public void setSeanses(Set<Seans> seanses) {
		this.seanses = seanses;
	}

}
