package tables;

// Generated 10.05.2016 10:16:44 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hall generated by hbm2java
 */
@Entity
@Table(name = "hall", catalog = "cinema")
public class Hall implements java.io.Serializable {

	private int hallId;
	private String name;
	private int numberOfSeats;
	private Set<Seans> seanses = new HashSet<Seans>(0);

	public Hall() {
	}

	public Hall(String name, int numberOfSeats) {
		this.name = name;
		this.numberOfSeats = numberOfSeats;
	}

	public Hall(String name, int numberOfSeats, Set<Seans> seanses) {
		this.name = name;
		this.numberOfSeats = numberOfSeats;
		this.seanses = seanses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "hall_id", unique = true, nullable = false)
	public int getHallId() {
		return this.hallId;
	}

	public void setHallId(int hallId) {
		this.hallId = hallId;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "number_of_seats", nullable = false)
	public int getNumberOfSeats() {
		return this.numberOfSeats;
	}

	public void setNumberOfSeats(int numberOfSeats) {
		this.numberOfSeats = numberOfSeats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hall")
	public Set<Seans> getSeanses() {
		return this.seanses;
	}

	public void setSeanses(Set<Seans> seanses) {
		this.seanses = seanses;
	}

}
