package tables;

// Generated 10.05.2016 10:16:44 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Movie generated by hbm2java
 */
@Entity
@Table(name = "movie", catalog = "cinema")
public class Movie implements java.io.Serializable {

	private int movieId;
	private String name;
	private String description;
	private String duration;
	private String earned_money;
	private String producer;
	private String genres;
	private int rating;
	
	@Column(name = "rating", nullable = false)
	public int getRating() {
		return rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	@Column(name = "producer", nullable = false)
	public String getProducer() {
		return producer;
	}

	public void setProducer(String producer) {
		this.producer = producer;
	}

	@Column(name = "genres", nullable = false)
	public String getGenres() {
		return genres;
	}

	public void setGenres(String genres) {
		this.genres = genres;
	}

	@Column(name = "duration", nullable = false)
	public String getDuration() {
		return duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	@Column(name = "earned_money", nullable = false)
	public String getEarned_money() {
		return earned_money;
	}

	public void setEarned_money(String earned_money) {
		this.earned_money = earned_money;
	}

	private Set<Seans> seanses = new HashSet(0);

	public Movie() {
	}

	public Movie(String name, String description) {
		this.name = name;
		this.description = description;
	}

	public Movie(String name, String description, Set<Seans> seanses) {
		this.name = name;
		this.description = description;
		this.seanses = seanses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "movie_id", unique = true, nullable = false)
	public int getMovieId() {
		return this.movieId;
	}

	public void setMovieId(int movieId) {
		this.movieId = movieId;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movie")
	public Set<Seans> getSeanses() {
		return this.seanses;
	}

	public void setSeanses(Set<Seans> seanses) {
		this.seanses = seanses;
	}

}
