package tables;

// Generated 10.05.2016 10:16:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Seans generated by hbm2java
 */
@Entity
@Table(name = "seans", catalog = "cinema", uniqueConstraints = {
		@UniqueConstraint(columnNames = "hall_id"),
		@UniqueConstraint(columnNames = "movie_id"),
		@UniqueConstraint(columnNames = "cinema_id") })
public class Seans implements java.io.Serializable {

	private int seansId;
	private Hall hall;
	private Cinema cinema;
	private Movie movie;
	private String datetime;
	private String price;
	private int freeSeats;
	private int occupiedSeats;

	public Seans() {
	}

	public Seans(Hall hall, Cinema cinema, Movie movie, String datetime,
			String price, int freeSeats, int occupiedSeats) {
		this.hall = hall;
		this.cinema = cinema;
		this.movie = movie;
		this.datetime = datetime;
		this.price = price;
		this.freeSeats = freeSeats;
		this.occupiedSeats = occupiedSeats;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "seans_id", unique = true, nullable = false)
	public int getSeansId() {
		return this.seansId;
	}

	public void setSeansId(int seansId) {
		this.seansId = seansId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hall_id", unique = true, nullable = false)
	public Hall getHall() {
		return this.hall;
	}

	public void setHall(Hall hall) {
		this.hall = hall;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cinema_id", unique = true, nullable = false)
	public Cinema getCinema() {
		return this.cinema;
	}

	public void setCinema(Cinema cinema) {
		this.cinema = cinema;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "movie_id", unique = true, nullable = false)
	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	@Column(name = "datetime", nullable = false, length = 10)
	public String getDatetime() {
		return this.datetime;
	}

	public void setDatetime(String datetime) {
		this.datetime = datetime;
	}

	@Column(name = "price", nullable = false, length = 7)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "free_seats", nullable = false)
	public int getFreeSeats() {
		return this.freeSeats;
	}

	public void setFreeSeats(int freeSeats) {
		this.freeSeats = freeSeats;
	}

	@Column(name = "occupied_seats", nullable = false)
	public int getOccupiedSeats() {
		return this.occupiedSeats;
	}

	public void setOccupiedSeats(int occupiedSeats) {
		this.occupiedSeats = occupiedSeats;
	}

}
